/** Canonical English positioning essay — not the protocol whitepaper. */
export const WHY_PACT_MARKDOWN = [
  "Every existing way to prove a business is real shares the same flaw: it is an *authority's claim*, not *evidence*. A credit bureau's report, a state registry entry, a bank statement, a LinkedIn history — all of them ask you to trust that someone else verified correctly. None of them produce something a stranger can check for themselves, from first principles, without trusting a gatekeeper.",
  "That flaw used to be tolerable. It isn't anymore. Generative AI did not create a new threat — it removed the last thing that made faking these signals expensive. A ten-year-old domain, a five-year LinkedIn history, a convincing bank statement: all of it can now be fabricated cheaply. The authorities did not get worse. The cost of lying to them collapsed.",
  'PACT does not ask you to trust an authority. It asks you to check a public record.',
  "Every claim PACT makes is derived from independent receiving mail systems — Gmail, Outlook, Yahoo, and others — that have no relationship with each other, no incentive to coordinate, and no awareness they are being used as evidence. Their aggregate, uncoordinated agreement over time is the proof. Not because PACT says so. Because anyone can recompute the published leaves and inclusion proofs against the on-chain Merkle root, without asking PACT's permission. Roots are on Base Sepolia today (testnet, permissioned publisher). Reporter-wrapper DKIM is verified at ingest, and the passing d=/selector plus keccak256 of the wrapper are committed in the leaf. The RFC822 itself is not published. What remains is narrower operator trust: leaf availability and that publisher key — not a change of thesis.",
  "That is the property incumbent proofs cannot retrofit. A credit bureau cannot become trustless — its business model *is* the trusted intermediary. A government registry cannot become trustless — it is definitionally an authority. A bank statement cannot become trustless — it is a document, and documents can be edited. PACT is not a better version of these. It sits in a different category: evidence you can recheck, not a claim you must accept.",
  "Here is what makes that durable, not just different: **the history PACT measures cannot be manufactured after the fact, at any price — including by PACT's own operators.**",
  'You can buy an aged domain. You can fabricate a LinkedIn history. You can build a shell company with perfect paperwork. What you cannot do is make yesterday happen earlier. PACT\'s history is built from real time passing while independent third parties were watching. There is no shortcut through time. That is not a product preference. It is a physical constraint PACT puts to work.',
  'This is why PACT does not compete on cost or convenience today, and does not need to. Existing methods are cheap and instant *because* they are shallow enough to fake cheaply and instantly. PACT is slow to build *because* a well-funded, patient, AI-equipped adversary still cannot buy a past they did not live. The slowness is not a limitation waiting to be optimized away. It is the point.',
  'Every other proof of legitimacy answers: *what did someone claim, and who is vouching for it?*',
  'PACT answers a different question: *what actually happened, for how long, witnessed by how many independent parties who had no reason to lie?*',
  'That question has never had a durable public answer before. Starting now, it does.',
].join('\n\n');
